### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by liu304424818** [yunionio/cloudpods-operator#564]
kubectl logs  -n onecloud  onecloud-operator-6f98c58bb8-w7ppb 
F0322 08:16:56.500557       1 main.go:132] init CRD resources: failed to create CRD: unable to create crd onecloudclusters.onecloud.yunion.io: the server could not find the requested resource

**Comment by zexi** [comment]
kubernetes 集群的版本是多少？

**Comment by zexi** [comment]
这个是k8s集群版本太高导致的，请参考这个文档：https://www.cloudpods.org/zh/docs/quickstart/k8s/ 在 1.20 以下的 k8s 集群上部署
